version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/the-anime-wire
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
    - location: scripts/install_dependencies.sh 
  ApplicationStart:
    - location: scripts/start_application.sh
  ApplicationStop:
    - location: scripts/stop_application.sh