version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing Node.js"
      - apt-get update
      - apt-get install -y curl
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - npm install -g yarn

  pre_build:
    commands:
      - echo "Installing dependencies for Django"
      - pip install -r requirements.txt
      - echo "Installing dependencies for React"
      - cd frontend
      - yarn install

  build:
    commands:
      - cd ..
      - echo "Building Django project"
      - python manage.py collectstatic --noinput
      - echo "Building React app"
      - cd frontend
      - yarn build

artifacts:
  files:
    - '**/*'
