# Generated by Django 4.2 on 2023-12-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_animecategories_animegenres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingServices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('streaming_name', models.CharField(max_length=255)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'streaming_services',
            },
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='streaming_services',
            field=models.ManyToManyField(related_name='user_streaming_services', to='app.streamingservices'),
        ),
    ]
