# Generated by Django 4.2 on 2023-12-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_streamingservices_profilesettings_streaming_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='prof_pic',
        ),
    ]
