# Generated by Django 4.2 on 2024-01-01 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profilesettings_prof_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecategories',
            name='examples',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
